// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $CuiaHeaderComponent_Component from "./islands/CuiaHeaderComponent/Component.tsx";
import * as $CuiaHeaderComponent_CuiaHeaderComponent from "./islands/CuiaHeaderComponent/CuiaHeaderComponent.tsx";
import * as $MainSlider_Component from "./islands/MainSlider/Component.tsx";
import * as $MainSlider_MainSlider from "./islands/MainSlider/MainSlider.tsx";
import * as $Menu from "./islands/Menu.tsx";
import * as $Slides_Component from "./islands/Slides/Component.tsx";
import * as $Slides_Slides from "./islands/Slides/Slides.tsx";
import * as $SolutionsSlider_Component from "./islands/SolutionsSlider/Component.tsx";
import * as $SolutionsSlider_SolutionsSlider from "./islands/SolutionsSlider/SolutionsSlider.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/CuiaHeaderComponent/Component.tsx":
      $CuiaHeaderComponent_Component,
    "./islands/CuiaHeaderComponent/CuiaHeaderComponent.tsx":
      $CuiaHeaderComponent_CuiaHeaderComponent,
    "./islands/MainSlider/Component.tsx": $MainSlider_Component,
    "./islands/MainSlider/MainSlider.tsx": $MainSlider_MainSlider,
    "./islands/Menu.tsx": $Menu,
    "./islands/Slides/Component.tsx": $Slides_Component,
    "./islands/Slides/Slides.tsx": $Slides_Slides,
    "./islands/SolutionsSlider/Component.tsx": $SolutionsSlider_Component,
    "./islands/SolutionsSlider/SolutionsSlider.tsx":
      $SolutionsSlider_SolutionsSlider,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
